name: Test
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install memcached
      run: sudo apt-get install memcached
    - name: Install ginkgo
      run: |
          go get github.com/onsi/ginkgo/v2/ginkgo@latest
          go get github.com/onsi/gomega/...
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    - name: Test
      run: ginkgo src/
